# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

container: kuritsu/tf-aws:0.15

steps:
- script: terraform --version
  name: TfVer

- script: terraform plan
  name: TfPlan
  condition: not(contains(variables['build.sourceBranch'], 'refs/heads/main'))

- script: terraform apply
  name: TfApply
  condition: contains(variables['build.sourceBranch'], 'refs/heads/main')
