trigger:
- "*"

pr:
- "*"

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    curl -O https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
    sudo apt-get update -y && sudo apt-get install -y unzip
    unzip terraform_0.15.5_linux_amd64.zip
    sudo chmod a+x terraform && sudo cp terraform /usr/bin
  name: InstallTf

- script: terraform --version
  name: Version

- script: terraform init
  name: Init
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

- script: terraform plan
  name: Plan
  condition: not(contains(variables['build.sourceBranch'], 'refs/heads/main'))
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

- script: terraform apply -auto-approve
  name: Apply
  condition: contains(variables['build.sourceBranch'], 'refs/heads/main')
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
