# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

version: 0.2

run-as: root

phases:
  version:
    commands:
      - terraform --version
      - terraform init

  apply:
    commands:
      - terraform plan
      - terraform apply
